spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wintersite
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      generate-ddl: true
